#!/bin/bash
#
# mci-lr        start/stop/status script
#
# chkconfig: - 64 36
# description: The mci-lr shared health record system
# processname: mci-lr
# config: /etc/default/mci-lr
# pidfile: /var/run/mci-lr/mci-lr.pid
### BEGIN INIT INFO
# Provides: mci-lr
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop mci-lr system,
# Description: BDSHR system
### END INIT INFO

export MCI_LR_USER=sharedhealth
export MCI_LR_RUN=/opt/mci-lr/bin/start.sh
export CUR_USER=`/usr/bin/whoami`

# load configuration
. /etc/default/mci-lr

create_dirs() {
    if [[ ! -e /var/run/mci-lr ]]; then
        ln -s /opt/mci-lr/var /var/run/mci-lr
    fi

    if [[ ! -e /var/log/mci-lr ]]; then
        mkdir /var/log/mci-lr
    fi
}
mci_lr_pid() {
        echo `ps -fe | grep "mci-lr.jar" | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(mci_lr_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService mci-lr is already running (pid: $pid)\e[00m"
    else
        # Start mci-lr
        create_dirs
        echo -e "\e[00;32mStarting mci-lr\e[00m"
        if [ `user_exists $MCI_LR_USER` = "1" ]  && [ "$CUR_USER" != "$MCI_LR_USER" ] ;
        then
                /bin/su $MCI_LR_USER -c $MCI_LR_RUN
        else
                sh $MCI_LR_RUN
        fi
  fi
  return 0
}
status(){
          pid=$(mci_lr_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService mci-lr is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService mci-lr is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating mci-lr\e[00m"
	kill -9 $(mci_lr_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0